# Generated by Django 5.1.2 on 2024-10-19 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTypesDBNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type_db_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedVideos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_ref_id', models.CharField(default='', max_length=1000)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('uploaded_date', models.DateTimeField()),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_uploaded_manually_by_user', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.CharField(blank=True, max_length=100, null=True)),
                ('completion_date', models.DateTimeField(blank=True, null=True)),
                ('desired_video_quantity', models.IntegerField()),
                ('uploaded_video_quantity', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.ordertypesdbnames')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_type', models.CharField(max_length=100)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RedditVideoOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_link', models.CharField(max_length=1000)),
                ('youtube_video_link', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('hashtags', models.CharField(max_length=5000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.orders')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(blank=True, max_length=100)),
                ('account_username', models.CharField(max_length=100)),
                ('auth_key', models.CharField(blank=True, max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('hashtags', models.CharField(max_length=5000)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.orders')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.generatedvideos')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeTwoVideosOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_primary_link', models.CharField(max_length=1000)),
                ('youtube_secondary_link', models.CharField(max_length=1000)),
                ('description', models.CharField(blank=True, max_length=5000, null=True)),
                ('hashtags', models.CharField(blank=True, max_length=5000, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.orders')),
            ],
        ),
    ]
