# Generated by Django 5.1.2 on 2024-10-14 20:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OrderTypesDBNames',
            fields=[
                ('order_type_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('order_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('username', models.CharField(max_length=100)),
                ('client_type', models.CharField(blank=True, max_length=100)),
                ('registered_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('order_status', models.CharField(blank=True, max_length=100)),
                ('completion_date', models.DateTimeField()),
                ('desired_video_quantity', models.IntegerField()),
                ('uploaded_video_quantity', models.IntegerField()),
                ('order_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.ordertypesdbnames')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.users')),
            ],
        ),
        migrations.CreateModel(
            name='RedditVideoOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reddit_link', models.CharField(max_length=1000)),
                ('youtube_video_link', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('hashtags', models.CharField(max_length=5000)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.orders')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccounts',
            fields=[
                ('account_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('account_type', models.CharField(blank=True, max_length=100)),
                ('account_username', models.CharField(max_length=100)),
                ('auth_key', models.CharField(blank=True, max_length=100)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.users', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedVideos',
            fields=[
                ('video_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('creation_date', models.DateTimeField()),
                ('uploaded_date', models.DateTimeField()),
                ('is_uploaded', models.BooleanField(default=False)),
                ('is_uploaded_manually_by_user', models.BooleanField(default=False)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.users', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserVideoOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=5000)),
                ('hashtags', models.CharField(max_length=5000)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.orders')),
                ('video_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.generatedvideos')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeTwoVideosOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_primary_link', models.CharField(max_length=1000)),
                ('youtube_secondary_link', models.CharField(max_length=1000)),
                ('description', models.CharField(max_length=5000)),
                ('hashtags', models.CharField(max_length=5000)),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_manager.orders')),
            ],
        ),
    ]
